theme: jekyll-theme-minimal

logo: https://github.com/ANU-WALD/ANU-WALD.github.io/raw/master/data_stack_wald.png

title: Hacking with Environmental Data
description: WALD's help page for geospatial hackers
